spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:mysql://${DB_URL}/large-scale?socketTimeout=2000
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 3000
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    show-sql: true

mail:
  email: ${MAIL_EMAIL}
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}
  debug: ${MAIL_DEBUG}
